---
author: "Vic Zhang"
title: "MA615 Formatting HW"
date: "9/18/2019"
output: pdf_document
fontsize: 30pt
---

```{r setup, include=FALSE}
library(kableExtra)
library(tidyr)
library(tidyverse)
library(esquisse)
library(knitr)
library(magrittr)
knitr::opts_chunk$set(echo = TRUE)
```


## Extract From: 
Bradley Efron and Trevor Hastie  
*Computer Age Statistical Inference: Algorithms, Evidence, and Data Science*    
*Cambridge University Press, 2016*  
*https://web.stanford.edu/~hastie/CASI_files/PDF/casi.pdf*  
\vspace{1cm}

\Large{\qquad Modern Bayesian practice uses various strategies to construct an appropriate “prior” $g(\mu)$ in the absence of prior experience, leaving many statisticians unconvinced by the resulting Bayesian inferences. Our second example illustrates the difficulty.}
\newline
\Large{
\textcolor{blue}{\textbf{Table 3.1}}
\textsl{Scores from two tests taken by 22 students},
\textcolor{olive}{\textsf{mechanics}}
and
\textcolor{olive}{\textsf{vectors}}
}

\begin{center}
\begin{tabular}{@{}llllllllllll@{}}
\toprule
\multicolumn{1}{c}{} & 1                      & 2  & 3  & 4  & 5  & 6  & 7  & 8  & 9  & 10 & 11 \\ \midrule
\textcolor{olive}{\textsf{mechanics}}            & 7                      & 44 & 49 & 59 & 34 & 46 & 0  & 32 & 49 & 52 & 44 \\
\textcolor{olive}{\textsf{vectors}}              & \multicolumn{1}{r}{51} & 69 & 41 & 70 & 42 & 40 & 40 & 45 & 57 & 64 & 61 \\ \bottomrule
\end{tabular}


\begin{tabular}{@{}llllllllllll@{}}
\toprule
\multicolumn{1}{c}{} & 12                      & 13  & 14  & 15  & 16  & 17  & 18  & 19  & 20  & 21 & 22 \\ \midrule
\textcolor{olive}{\textsf{mechanics}}            & 36                      & 42 & 5 & 22 & 18 & 41 & 48  & 31 & 42 & 46 & 63 \\
\textcolor{olive}{\textsf{vectors}}              & \multicolumn{1}{r}{59} & 60 & 30 & 58 & 51 & 63 & 38 & 42 & 69 & 49 & 63 \\ \bottomrule
\end{tabular}
\end{center}

\Large{\qquad Table 3.1 shows the scores on two tests, \textcolor{olive}{\textsf{mechanics}} and \textcolor{olive}{\textsf{vectors}}, achieved by $n=22$ students. The sample correlation coefficient between the two scores is $\hat{\theta}=0.498$,}
$$
\hat{\theta} = \sum_{i=1}^{22}(m_i-\bar{m})(v_i-\bar{v}) \bigg{/}\bigg{[} \sum_{i=1}^{22}(m_i-\bar{m})^2\sum_{i=1}^{22}(v_i-\bar{v})^2 \bigg{]}^{1/2}
$$
with *m* and *v* short for \textcolor{olive}{\textsf{mechanics}} and \textcolor{olive}{\textsf{vectors}}, $\bar{m}$ and $\bar{v}$ their averages.



